### ISSUE TITLE
hc-segment-fetcher

### ISSUE THREAD

**Issue by uni2u** [uni2u/difs-cxx#11]
### 내용
- HashChain 검증을 위함
  - difs 는 producer 로 부터 데이터를 저장하기 전 패킷을 검증할 수 있어야 함
  - ndn-cxx/util/segment-fetcher.hpp 를 재활용 할 수 있도록 함

### 현재 코드 구성 (hc-segment-fetcher.cpp)
- segment-fetcher 는 private 으로 구성되어 상속의 문제가 있음
- segment-fetcher 를 재활용한 hc-segment-fetcher 를 구현

### difs 적용
- 검증은 크게 두가지로 구성됨
  - producer 의 저장 요청을 처리할 때
    - difs 노드는 저장전 데이터를 검증하고 저장
  - consumer 가 difs 의 데이터를 처리할 때
    - consumer 는 difs 를 통해 데이터를 제공받은 후 검증하고 사용
 
#### difs 라이브러리
- difs 라이브러리를 통해 사용자 (producer, consumer) 는 쉽게 HashChain 을 활용
  - 동일한 HashChain Validation 라이브러리 활용 가능

#### producer 흐름도
- producer 가 데이터 저장을 요청하는 application (ndnputfile) 을 통해 difs 노드로 insert 요청
  - `ndn://<common-name>/insert`
- difs 는 데이터 완전체를 가지고 있는 producer 노드로 데이터 요청
  - `ndn://<producer-node>/<content-name>/<segment num>/...`
- producer 로 부터 데이터 패킷이 제공되면
  - difs 노드는 validation (hashchain 검증) 후 데이터를 mongodb 에 저장

#### consumer 흐름도
- consumer 가 데이터를 요청하는 application (ndngetfile) 을 통해 difs 노드로 데이터 요청
  - `ndn://<difs-node-name>/<data-name>/<segment num>/...`
- difs 로 부터 데이터 패킷이 제공되면
  - consumer 는 validation (hashchain 검증) 후 데이터 확인

#### ndnputchunk 테스트
- 최종적으로 difs 의 ndnputfile 에 추가되어야 함
- difs-cxx 및 difs 수정 후 빌드 반복의 오버헤드가 있기 때문에 ndn-tools 활용
  - ndn-tools/tools/chunks/putchunks/producer.cpp
  - 테스트 후 difs ndnputfile (insert) 코드로 반영

#### 주의
- 성능 개선을 위한 공통 코드가 있다면 hc-key-chain 등의 라이브러러에 추가함

**Comment by uni2u** [comment]
[질의] https://github.com/uni2u/difs-cxx/issues/8#issuecomment-844858178

**Comment by uni2u** [comment]
[응답] https://github.com/uni2u/difs-cxx/issues/8#issuecomment-844885471

**Comment by uni2u** [comment]
### 검증 순서
- 프로토콜 레이어에서 순서 보장
  - NDN 에서 지원하는지는 확인하지 않았음
  - 일반적으로 face 생성시 tcp 를 사용한다면 순서대로 진행
    - TCP 프로토콜이 in-order delivery (순서보장)
    - INC 의 예 (실시간 블랙박스 영상)
      - 패킷이 순서대로 오지 않은 경우가 있었는지요?
      - 그외의 테스트에서 순서대로 오지 않은 경우가 있었는지요?

#### MW-NFD 에서
  - thread 를 사용하여 동시에 코어 할당을 하는 관계로 순서를 보장하지 않음
    - HashChain 을 사용하기에 무리가 있음
      - memory 에 전체 패킷을 쌓고, re-ordering 을 진행하고, hash 검증
  - 랜덤 검증
    - 순서대로 들어온 경우에만 hash 검증
      - 순서대로 들어오지 않는 경우에는 그냥 받아들이고
      - 순서대로 들어온 경우에 hash 검증을 진행하고
      - 검증이 20% 이상 된 경우에는 검증 완료
      - 예) [0][2][3][1] 형식으로 들어온 경우
        - [0]: 첫번째 패킷으로 ECDSA 검증
        - [2]: 이전 패킷이 [0] 이기에 검증할 수 없기 때문에 건너뜀
        - [3]: 이전 패킷이 [2] 이기에 검증 가능 (hash 검증)
        - [1]: 이전 패킷이 [3] 이기에 검증할 수 없기 때문에 건너뜀
        - 전체 패킷 4개 중 [0], [3] 이 검증되어 50% 이상 검증이 되었기에 검증완료
      - 예) [1][0][3][2] 형식으로 들어온 경우
        - [1]: 첫번째 패킷으로 검증을 할 수 없기 때문에 건너뜀
        - [0]: 원 데이터의 첫번째 패킷으로 ECDSA 검증 가능
        - [3]: 검증할 수 없기 때문에 건너뜀
        - [2]: 검증할 수 없기 때문에 건너뜀
        - 전체 패킷 4개 중 [0] 이 검증되어 25% 이상 검증이 되었기에 검증완료

---

### 성능 향상
- 그룹 HashChain
  - 첫번째 패킷: ECDSA
  - 그룹의 첫번째 패킷: sha256 (다음 그룹의 첫밴째 패킷의 hash)
    - 그룹 내부: sha256

```
[1][2][3][4][5][6][7][8][9][10]

- [1]: ECDSA
- Group1
  - [2]: HashChain 0 (Group2 [6] hash)
  - [3]: sha256
  - [4]: sha256
  - [5]: sha256
- Group2
  - [6]: HashChain 1 (Group3 [10] hash)
  - [7]: sha256
  - [8]: sha256
  - [9]: sha256
- Group3
  - [10]: HashChain 2 (00...00 hash)
```

**Comment by justin-labry** [comment]
pseudo code를 작성하여 보았습니다. 이런식으로하면 문제가 없을것 같습니다. 

```
segmentNo = 0;

SegmentFetcher::afterValidationSuccess(Data data) {

  m_data.insert(segmentNo_from_name, data);
  
  If (hashChainValidator is not running) {
  HashChainValidator start.
  }
}

HashChainValidator() {
        while( number of data in m_data) {
	item = m_data.find(segmentNo, data);
	verifyData(data);
	if(verified) segmentNo ++;
	afterSegmentValidated(newData);
        }

	while(is segmentNo != finalBlockId && timeout not occur) {
		item = m_data.find(segmentNo, data);
		verifyData(data);
		if(verified) {segmentNo ++;
                timeout renewed;
                }
		afterSegmentValidated(newData);
	}
}
```

**Comment by taewoong0627** [comment]
### **windowSize 관련 이슈**

아래와 같은 옵션으로 테스트를 진행해본 결과 windowSize는 SlidingWindow 방식으로 돌아가는 것이 아닌것으로 보입니다.
테스트 진행 방식은 0번 Data를 보낸 후 1번 Data가 아닌 3번 Data를 보냈을 때 SegmentFetcher 에서 받지 못한 1번 Data를 요청하지 않고, 4번 Data를 요청하며, 마지막 Data를 받았을 때 받지 못한 1번 Data를 요청하고 있습니다. 위와 같이 동작하는 것으로 보아 windowSize는 Interest의 최대 요청 크기 인것으로 보입니다.
```
ndn::util::SegmentFetcher::Options options;
options.initCwnd = 4;
options.useConstantCwnd = true;
```


![스크린샷, 2021-05-24 13-43-23](https://user-images.githubusercontent.com/64938848/119297580-3b3e7f80-bc96-11eb-9f83-10724a57d3f0.png)
![스크린샷, 2021-05-24 13-44-05](https://user-images.githubusercontent.com/64938848/119297585-3e397000-bc96-11eb-8abc-7f45974a8734.png)

위에 말씀해주신것처럼 랜덤 인증을 진행하려면, 4개의 데이터를 다 받은 후 다음 4개의 데이터 요청을 보내야하는 방식이 필요하지만, 그렇게 동작하지 않으므로 SegmentFetcher 를 수정해 진행하는 방법밖에 없을 것 같습니다.

SegmentFetcher 를 직접 수정하여 진행을 해야할지, 아니면 다른 방식을 찾아 진행을 해야할지 의견 부탁드립니다.

**Comment by uni2u** [comment]
- window 사이즈는 Interest 를 담아 보내는 그릇입니다
  - window_size=1 은 1개의 Interest 를, window_size=10 은 10 개의 Interest 를 담아서 보내게 됩니다.
  - TCP 의 window size 부분과 같다고 보입니다만
  - 단, 데이터 마지막이 전송된 후 hold 된 segment 데이터 요청은 코드 확인이 필요합니다.
  
```
Interest segNo: 0
Receive segNo: 0

# window size = 4
Interest segNo: 1
Interest segNo: 2
Interest segNo: 3
Interest segNo: 4

# data 를 하나 받음: window size = 3
Receive segNo: 3

# window size 여유가 있기에 다음 Interest 전송: window size = 4
Interest segNo: 5
.
.
.
```
---
[정리]
- 랜덤 인증 관련
  - 랜덤 인증은 window size 와 상관 없이 진행가능 합니다.
    - 즉, intCwnd = 1 을 기본 동작으로 하며
    - ECDSA 가 적용된 첫번째 segment, 연속되어 들어오는 segment 인 경우에만 검증하고,
    - 연속되지 않는 경우에는 검증을 하지 않고 skip 하여
    - 전체 segment 숫자 대비 50% 이상 검증에 성공하면 검증 완료로 하는 개념입니다.
  - window 사이즈 적용
    - 추후 성능에 대한 이슈가 발생하면 성능을 높이기 위한 방편으로 활용합니다.
    - 이 경우 검증은 마찬가지로 동작하면 될 듯 합니다.
      - window 사이즈가 적용되어도 segment 데이터가 전송되며
      - 연속된 segment 인 경우에는 검증하고, 연속되지 않는 경우에는 검증을 하지 않고 skip 함
      - 데이터 전체 segment 대비 50% 이상 검증된 경우 검증 완료

**Comment by taewoong0627** [comment]
### hc-segment-fetcher 

랜덤 인증 관련하여, 아래와 같이 구현하였습니다.
우선 들어 온 데이터의 semgent와 signature block 을 저장합니다. 그 다음 데이터가 들어왔을 때 segment 를 비교하여 바로 이전 데이터일 경우 key 를 비교하여, 같지 않을 시 onError 를 호출하고, 같을 경우 success_count 를 올려줍니다. 마지막 데이터가 들어 왔을 때 success_count 가 총 segment 개수의 절반을 넘지 못할 경우 onError를 호출합니다.

여기서 궁금한점은 처음부터 중간 데이터까지 바로 50% 검증이 완료되었을 때 이후 데이터는 아예 검증을 하지 않고 검증 완료로 볼 것인지, 그 뒤에 오는 데이터도 검증을 진행하여 key 값이 다를 경우 onError로 처리해야하는지 입니다. 의견을 내주신 방식대로라면 segment 번호가 꼬였을 경우에 앞에 데이터를 차례대로 **전부 검증**하지 못하기 때문에 50% 이상 검증된 경우 완료이지만, 데이터가 차례대로 들어올 경우 50%는 정상 50%는 비정상일 수 있어 문제가 발생할 수 있습니다.

성능을 우선적으로 생각하셔서, 어떤 상황이든 50%가 넘을 경우 그 뒤에 오는 데이터들은 검증하지 않으실건지, 데이터의 신뢰성이 우선인지에 대해 얘기해주시면 감사하겠습니다. 개인적인 생각으로는 순서가 꼬일 경우 50% 검증을 이용하는것이 맞고, 데이터가 차례대로 들어올 경우에는 전부다 검증을 하는것이 맞다고 생각하고 있습니다.

```
void 
HCSegmentFetcher::randAfterValidationSuccess(const Data& data) {
  auto content = data.getContent();
  content.parse();

  int segment = data.getName().get(-1).toSegment();

  if (segment != 0) {
    if (segment - 1 == before_segment) {
      if(memcmp((void*)data.getSignatureValue().value(), (void*)before_signature->value(), data.getSignatureValue().value_size())) {
        onError(HASHCHAIN_ERROR, "Failure hash key error");
      } else {
        success_count++;
        afterSegmentValidated(data);
      }
    } else {
      afterSegmentValidated(data);
    }
  } else {
    success_count++;
    afterSegmentValidated(data);
  }

  int finalBlockId = data.getFinalBlock().value().toSegment();
  if (segment == finalBlockId) {
    if (success_count < finalBlockId / 2) {
      onError(HASHCHAIN_ERROR, "Failure hash key error");
    }
  }

  before_segment = segment;
  before_signature = std::make_shared<Block>(content.get(tlv::SignatureValue));
}
```

**Comment by uni2u** [comment]
- 저도 동의합니다.
  - 데이터가 차례대로 들어오는 경우 (보통의 경우)
    - segment 마다 검증
  - 데이터가 차례대로 들어오지 않는 경우
    - skip 검증을 진행 (50% 이상)
---
[정리]
- segment 검증
  - 데이터가 순서대로 들어오는 경우
    - segment 마다 검증 실행 
  - 데이터가 순서대로 들어오지 않는 경우
    - 랜덤 검증 실행

**Comment by justin-labry** [comment]
randAfterValidationSuccess에서 rand는 어떤 뜻인가요?

**Comment by uni2u** [comment]
@justin-labry
- hash-chain 의 1차 진행으로 검증시 순서대로 들어오지 않은 경우 건너뛰고 검증하는 내용이 포함된 부분
  - 이 부분은 추후 2차 진행 예정
