### ISSUE TITLE
HashChain library 체크 및 검토사항

### ISSUE THREAD

**Issue by uni2u** [uni2u/difs-cxx#3]
## Overview

- 현재 (2021.03.05. 기준) difs-cxx 의 hash-chain 검토
  - 적어도 한 세트 (ndnputchunk -> data validate) 동작 확인이 필요함
  - 빠르게 기능적인 검토를 할 수 있도록 부탁드림

### flow overview

- producer: ndnputchunk (ndnputfile) 실행
  - block 구성
- DIFS: producer 로 _Interest_ 를 보내고 _data_ 를 받음
  - _data_ 는 mongoDB 로 저장시 validation 과정을 거쳐야 함

```
+----------+                  +------+
| producer |                  | DIFS |
+----------+                  +------+
     |---------ndnputfile-------->|
 +---|                            |
 |   |                            |
block|                            |
 |   |                            |
 +---|                            |
     |<--------  200 OK  ---------|
     |<--------interest01---------|
     |---------segment01--------->|
     |                            |---+
     |                            |   |
     |                            | hash-fetcher (afterValidationSuccess)
     |                            |   |
     |                            |---+
     |<--------interest02---------|
     |---------segment02--------->|
```

### hash-chain 블록 구성

- sha256 을 사용하기 때문에 32 byte 가 되어야 함

```
+----------------------+         +--------------+         +--------------+
|+--------------------+|         |+------------+|         |+------------+|
||data                ||         ||data        ||         ||data        ||
|+--------------------+|         |+------------+|         |+------------+|
||DigestSHA256        || <--+    ||DigestSHA256|| <--+    ||000000000000||
|+--------------------+|    |    |+------------+|    |    |+------------+|
+----------------------+    |    +--------------+    |    +--------------+
|SignatureSha256WithRsa|    +--- |DigestSHA256  |    +--- |DigestSHA256  |
+----------------------+         +--------------+         +--------------+
```

---

## ndnputchunk

- `ndnputchunk` 내용은 추후 `ndnputfile` 로 취합되어야 함
  - block 을 만드는 부분에서
    - reverse_end (데이터 스트림의 첫부분) 는 `SignatureSha256WithRsa` 로 함
    - 그 외 `DigestSHA256` 으로 함
- 이 내용은 바로 진행
  - difs/hash-chain 의 ndnputfile 에 일부 구현되어 있기 때문에 비교적 적용이 쉬울 것으로 판단
  - 최대한 빠르게 ndnputchunk 에 해당 기능을 적용하여 hashchain 관련 테스트 진행
    - ndnputchunk 에 우선 적용하는 이유는 difs 의 ndnputfile 에 적용시 인스톨, 설정 등의 시간이 걸리기 때문
  - 테스트 후 difs 의 ndnputfile 에 hashchain 관련 전체 기능 적용

## key-chain

- `key-chain` 을 상속받는 `hash-chain-key` 를 새로 만들어야 함
  - `sign` 에 next-hash 가 들어가고 current-hash 를 block type 으로 return 하여야 함
    - 현재, void 로 선언되어 있음
- 이 내용은 바로 진행

## segmentfetcher

- `segmentfetcher` 를 상속받는 `hash-fetcher` 를 새로 만들어야 함
  - first segment 처리 부분 확인 및 추가 (next-hash 가 empty 인 경우 next-hash 가 current-hash 로 됨)
  - afterValidationSuccess 에서 current-hash 와 next-hash 의 매치가 되지 않으면 exception 처리
- 이 내용은 바로 진행
  - difs 의 디렉토리 및 mongoDB 에 저장하기 전 검증시 사용
  - 추후, difs 에 포함되어야 함

## security validation config

- difs 의 repo-ng.conf 의 validator 는 type any 로 함
  - hash chain 의 validator 는 segmentfetcher 를 사용할 수 있도록 하기 위함
  - type any 는 validator 를 사용하지 않고 by pass (The following rule disables all security in the repo)
- 이 내용은 hashchain 기본 동작 확인이 끝난 후 진행

```
  trust-anchor
    {
      type any
    }
```

## new signature type

- 새로운 signature type 인 (SignatureWithHashchain) 정의가 필요함
- 이 내용은 hashchain 기본 동작 확인이 끝난 후 진행

**Comment by uni2u** [comment]
- 간략하게 위 개념이 어느정도 보이는 코드를 3월 11일 이전에 commit 될 수 있었으면 합니다.
  - ndnputchunk: 블럭 만드는 부분 수정
  - key-chain: void 로 되어 return 이 없는데 ndnputchunk 의 producer.cpp 에서 블록 만드는 부분에서 사용할 수 있도록 수정
  - segmentfetcher: validation (current hash 와 next hash 비교) 을 사용할 수 있도록 수정 (ndncatchunk?)

**Comment by justin-labry** [comment]
해당 부분의 pseudo code를 제가 한번 작성해보았습니다. 구현시 참고해 주세요.

```
producer.cpp
void
Producer::populateStore(std::istream& is)
{
  BOOST_ASSERT(m_store.empty());

  if (!m_options.isQuiet)
    std::cerr << "Loading input ..." << std::endl;

  std::vector<uint8_t> buffer(m_options.maxSegmentSize);
  while (is.good()) {
    is.read(reinterpret_cast<char*>(buffer.data()), buffer.size());
    const auto nCharsRead = is.gcount();

    if (nCharsRead > 0) {
      auto data = make_shared<Data>(Name(m_versionedPrefix).appendSegment(m_store.size()));
      data->setFreshnessPeriod(m_options.freshnessPeriod);
      data->setContent(buffer.data(), static_cast<size_t>(nCharsRead));
      **// It need to check if data is the last sement.
      // data->setFinalBlock(ndn::name::Component::fromSegment(final));**
  }
      m_store.push_back(data);
    }
  }

  if (m_store.empty()) {
    auto data = make_shared<Data>(Name(m_versionedPrefix).appendSegment(0));
    data->setFreshnessPeriod(m_options.freshnessPeriod);
    m_store.push_back(data);
  }

  m_startTime = time::steady_clock::now();

  auto finalBlockId = name::Component::fromSegment(m_store.size() - 1);

  Block nextHash; // It should be filled with 0x0000 (20bytes)
  for (auto it = m_store.rbegin(); it != m_store.rend(); it++) {
    Data& data = **it;
    data.setFinalBlock(finalBlockId);
    **// if( it == reverse_end)
    // m_keyChain.sign(data, nextHash, RSA_SHA256); 
    nextHash = m_keyChain.sign(data, nextHash, m_options.signingInfo);**
    std::cout << "data.content type: " << data.getContent().type() << std::endl;
  }
  
  // auto timeElapsed = time::steady_clock::now() - m_startTime;
  boost::chrono::duration<double, boost::chrono::seconds::period> timeElapsed = time::steady_clock::now() - m_startTime;
  
  std::cout << "Time elapsed: " << timeElapsed << std::endl;
  //exit(0);

  if (!m_options.isQuiet)
    std::cerr << "Created " << m_store.size() << " chunks for prefix " << m_prefix << std::endl;
}


key-chain.cpp

Block
KeyChain::sign(Data& data, const ndn::Block& nextHash, const SigningInfo& params)
{
  Name keyName;
  SignatureInfo sigInfo;
  std::tie(keyName, sigInfo) = prepareSignatureInfo(params);
  
  // Prepend hash to hash content block
  Block block = Block(tlv::Content);
  block.push_back(data.getContent());
  block.push_back(nextHash);
  data.setContent(block);

  data.setSignatureInfo(sigInfo);

  EncodingBuffer encoder;
  data.wireEncode(encoder, true);

  Block sigValue(
    tlv::SignatureValue,
    sign({{encoder.buf(), encoder.size()}}, keyName, params.getDigestAlgorithm()));

  data.wireEncode(encoder, sigValue);

  **//It should return digest-sha256 of current data**
}

segment-fetcher.cpp
void
SegmentFetcher::afterValidationSuccess(const Data& data, const Interest& origInterest,
                                       std::map<uint64_t, PendingSegment>::iterator pendingSegmentIt,
                                       const weak_ptr<SegmentFetcher>& weakSelf)
{
  if (shouldStop(weakSelf))
    return;

  // We update the last receive time here instead of in the segment received callback so that the
  // transfer will not fail to terminate if we only received invalid Data packets.
  m_timeLastSegmentReceived = time::steady_clock::now();

  m_nReceived++;

  // It was verified in afterSegmentReceivedCb that the last Data name component is a segment number
  uint64_t currentSegment = data.getName().get(-1).toSegment();
  m_receivedSegments.insert(currentSegment);

  // Add measurement to RTO estimator (if not retransmission)
  if (pendingSegmentIt->second.state == SegmentState::FirstInterest) {
    BOOST_ASSERT(m_nSegmentsInFlight >= 0);
    m_rttEstimator.addMeasurement(m_timeLastSegmentReceived - pendingSegmentIt->second.sendTime,
                                  static_cast<size_t>(m_nSegmentsInFlight) + 1);
  }

  // Remove from pending segments map
  m_pendingSegments.erase(pendingSegmentIt);

  // Split content into hash and content

  Data newData = data;
  
  ndn::Block currentHash = data.getSignatureValue();
  
  // compare currentHash vs nexthash
  **// ndn::Block nextHash = nextHash.value();
  // if nextHash.value_size() == 0 
  // set FirstSegment = true 
  // nextHash = currentHash; 
  // break to next phase;**

  if (memcmp(currentHash.value(), nextHash.value(), currentHash.value_size()) != 0) {
    // return false
  }

  Block content = data.getContent();
  if (content.type() == tlv::HashContent) {
    // HashContent hashContent; <- this type needs to be addressed. 
    // hashContent.wireDecode(data.getContent());

    // TODO: Check prev hash data matching current block's hash
    // nextHash = hashContent.getHash();

    // newData.setContent(hashContent.getData());
  }

```

**Comment by uni2u** [comment]
- 이해가 가지 않는 부분 질문 남겨주세요.
  - 텍스트로 표현에 한계가 있을 수 있습니다.
  - 여의치 않는 경우 오늘 (3월 5일) 오후에 온라인으로 설명을 진행하겠습니다.
    - 온라인은 ETRI 에서 화면 공유 및 마이크 사용이며 듣고 질문을 채팅창을 통해 남기는 것으로 하려고 합니다.

**Comment by Kjwon15** [comment]
당장 필요한 것:
* nextHash 받아서 이어 붙이도록 적용
  * 이를 위해 sign 함수 리턴 타입 변경
* 첫 블럭은 SHA256이 아닌 RSA로 사이닝
* catchunk에서 해시 검증

---

이어서 할 것:
* key-chain을 상속 받아 새로 구현
* TLV 타입 새로 만들기

---

이렇게 이해했는데 맞나요?

**Comment by uni2u** [comment]
네 큰 틀로는 맞습니다.

관련하여 문의가 생기면 바로바로 코멘트 남겨주시기 바랍니다.

**Comment by Kjwon15** [comment]
sign 함수의 시그니처를 바꿀 필요는 없어 보입니다. sign 이후에 `nexthash = data.getSignatureValue();`를 해 주면 되는군요

**Comment by uni2u** [comment]
- 수정 내용은 master 브렌치에 반영될 수 있도록 합니다.

**Comment by uni2u** [comment]
- ndnputchunk 수정 확인 예정 (@justin-labry)
  - https://github.com/Kjwon15/ndn-tools/commit/96c1ee6a2394475f94f903a6ac1df0580985ca41

**Comment by uni2u** [comment]
```
[메일 내용]
관련하여 지금 진행 중인 hash-chain ndn-cxx의 진행 상황에 대해서 이야기 들을 수 있을까요?
예를 들어.. 이런 이런 부분의 해결 방법을 찾고 있다든지... 
이런 부분은 조금 애매하다... TLV추가가 까다롭다... 아니면 어려운 부분은 없고 단순히 코딩 작업만 진행하고 테스트하면 된다든지요.

---

[답변]
지금 현재 상태가 TLV를 이용해서 Content 안에 RealContent, NextHash 둘을 같이 넣는 방식인데요.
디버그를 찍어 보면 사이즈가 늘어나는 걸로 보아 실제로 해시가 추가는 되는 것 같은데 어째 분리가 잘 안 됩니다. TLV를 잘못 넣었거나 분리 하는 방법을 제대로 못 찾고 있는 것으로 추정 됩니다.

---

[의견]
ndnputchunks의 producer.cpp를 보면 아래와 같은 내용이 있습니다.
그런데 m_options.maxSegmentSize 크기로 데이터를 넣고 
해시를 32바이트를 추가하는데... 여기서 문제가 발생하는것 아닐까요?
m_options.maxSegmentSize - 32; 하고 해시를 넣어야 하는것 아닐지요?
```

**Comment by uni2u** [comment]
```
+------------------------------------------+
|                   Name                   |
+------------------------------------------+
|                 MetaInfo                 |
|(ContentType,FreshnessPeriod,FinalBlockID)|
|(appMetaInfo=nexthash?)                   |
+------------------------------------------+
|                  Content                 |
+------------------------------------------+
|                 Signature                |
+------------------------------------------+
|SignatureInfo                             |
|            +----------------------------+|
|            | SignatureType              ||
|            +----------------------------+|
|            | KeyLocator                 ||
|            +----------------------------+|
+------------------------------------------+
|              SignatureValue              |
+------------------------------------------+
```

- appMetaInfo 를 활용하는 방안
  - appMetaInfo = next-hash 적용

**Comment by justin-labry** [comment]
ndn::MetaInfo nextHash(block);
  data.setMetaInfo(nextHash);
뭐 이런식으로 keychain의 sign 함수에 들어가겠지요 ^^

**Comment by uni2u** [comment]
- tlv 사용하지 않고 데이터 앞 부분에 32바이트 hash 를 추가
- 검증시 해당부분 분리하여 검증

- difs-cxx commit
  - https://github.com/uni2u/difs-cxx/commit/3fae503a1afdf43378e34cade4009d5cc527b801
- ndn-tools commit
  - https://github.com/Kjwon15/ndn-tools/commit/79b5a4f53c95e77788da5c2d8dce7ff4f5ab8d9d
  - https://github.com/Kjwon15/ndn-tools/commit/9c973679b3764d93712b4f02c53989ef537e86cc

```
ndn-cxx 에서 해시체인 구현 중 tlv를 사용하지 않고 그냥 32바이트 바이너리를 데이터 앞에 프리펜드 하고 읽을 때는 다시 분리하여 검증하는 방식으로 수정을 완료하였습니다.

uni2u/difs-cxx@hash-chain
kjwon15/ndn-tools@use-hashchain
```

@justin-labry 검토 예정

**Comment by justin-labry** [comment]
@uni2u 
네, 저도 코드 위주로 확인하였습니다. (기존의 docker위에서 했을때는 버전문제 0.7.0과 0.7.1등 마이너 버전의 문제가 좀 문제가 있는 것 같아서요. 내일 다시 한번 클린하게 시도해 볼 예정입니다.) 
일단
1. ndnputchunk의 내용을 ndnputfile
2. KeyChain을 확장하는 HcKeyChain
3. difs에는 HashChainSegmentFetcher(SegmentFetcher.hpp를 상속하는)를 사용하여 검증하는 루틴이 추가적으로 필요한것으로 생각됩니다. 
4. 지금 형태로 tlv를 사용하지 않는 방식으로 마무리 해봅시다.

**Comment by justin-labry** [comment]
@uni2u , @Kjwon15 

번거로운때문에 bytes 형태로 진행하려고 했으나 4번은 고민 결과...
bytes 형태로 컨텐츠에 넣는 경우는 segmentFetcher에서 검사하고 nextHash를 제거할 경우 다시 싸이닝을 해야 하는 오버헤드가 있고요.
다시 싸이닝을 안하는 경우는 유저가 컨텐츠에서 hash bytes를 제거해야 하는 오버헤드가 있습니다.
반면 tlv를 쓰면 그런 2가지 오버헤드가 없네요 ^^
tlv 형태로 하는것으로 제안드립니다.

**Comment by uni2u** [comment]
DIFS 가 패킷을 디렉토리/mongodb 에 저장함에 있어 next-hash 가 포함된 형태로 저장되어야 할 것으로 생각됩니다.
그래야 ndngetfile 통해 요청할 때 저장된 패킷 그대로 보낼 수 있습니다.

순수 데이터만 분리하여 저장하는 경우 다시 chain 을 만들고 signature 를 붙이는 등의 오버헤드가 발생합니다.
데이터를 받는 사람 입장에서는 콘텐츠에서 next-hash 를 분리하고 데이터를 추출하는 오버헤드가 발생합니다.

이런 이유를 생각할 때 tlv 에 next-hash 를 담는 형태가 가장 이상적인 방법이라 생각됩니다.
하여 appMetaInfo 를 활용하는 방안을 시도해보는 것이 필요하다고 생각됩니다.

어떻게 생각하시나요?

**Comment by uni2u** [comment]
## Hash-Chain 관련 내용 다음과 같이 우선 정리합니다.

- https://github.com/uni2u/difs-cxx/commit/3fae503a1afdf43378e34cade4009d5cc527b801
  - @justin-labry 체크 (ndn-cxx0.7.1 기반) 이후 master 로 merge
- hash-chain 관련 일은 **4월 중순 (~04.16.)** freezing 하기 위함
  - 아래 내용을 빠르게 진행
  - 논문의 결과로 사용하기 위함
    - 지난해까지 저장소 본연의 기능에 대한 논문이었다면
    - 이번에는 저장소 성능을 높이기 위한 hash-chain 라이브러리가 주된 내용 

##

### difs-cxx

#### hc-key-chain.cpp

- ndn-cxx/security/key-chain.hpp 를 상속함
- key-chain.cpp 에 작성한 hash-chain 관련 내용만 포함될 수 있도록 함
  - ndn-cxx 와 분리하여 관리할 수 있도록 하기 위함

#### hc-segment-fetcher.cpp

- ndn-cxx/util/segment-fetcher.hpp 를 상속함
- hash-chain 을 검증할 수 있는 루틴이 포함될 수 있도록 함

#### tlv 를 활용한 next-hash 구성

- 현재, difs-cxx 의 hash-chain 브렌치에 next-hash 구성은 데이터 앞 32 바이트를 추가하는 형태
- 오버헤드를 줄이기 위한 방안으로 tlv 에 next-hash 를 구성할 수 있도록 함
  - appMetaInfo 로 정의된 tlv 를 next-hash 로 사용
- **위 내용은 제안사항으로 가능/불가능 여부를 먼저 판단할 필요가 있음**
- **시간이 소요되는 경우 tlv 를 활용한 next-hash 구성은 동적노드구성 이후로 미룸**

#### ndn-cxx0.7.1 적용

- ndn-cxx0.7.1 로 업데이트 되면서 여러 수정이 진행됨
  - signature 및 validator 관련 수정이 진행된 관계로 이를 수용할 필요가 있음
- 특히, validator 관련 버그를 발견하고 NDN 커뮤니티에 리포팅한 관계로 버그 수정 기능이 반드시 필요함
- **위 내용은 NDN 커뮤니티의 스케줄에 따라 진행할 예정**

##

### DIFS 저장소

#### ndnputfile

- ndnputchunk 에 작성된 hash-chain 관련 내용 ndnputfile 적용
  - DIFS 의 hash-chain 브렌치

#### write-handler.cpp

- 현재, DIFS 의 write_handler 에서 SegmentFetcher 를 사용하여 segInit, onSegmentData, onSegmentTimeout 에 사용중
  - hc_segment_fetcher 를 활용하여 데이터가 DIFS 에 저장되기 전 hash-chain 검증할 수 있도록 함
  - DIFS 의 hash-chain 브렌치
