### ISSUE TITLE
Hash-Chain (TLV) 관련 우선 정리

### ISSUE THREAD

**Issue by uni2u** [uni2u/difs-cxx#8]
## Hash-Chain 관련 내용 다음과 같이 우선 정리합니다.

- https://github.com/uni2u/difs-cxx/commit/3fae503a1afdf43378e34cade4009d5cc527b801
  - @justin-labry 체크 (ndn-cxx0.7.1 기반) 이후 master 로 merge
- hash-chain 관련 일은 **4월 중순 (~04.16.)** freezing 하기 위함
  - 아래 내용을 빠르게 진행
  - 논문의 결과로 사용하기 위함
    - 지난해까지 저장소 본연의 기능에 대한 논문이었다면
    - 이번에는 저장소 성능을 높이기 위한 hash-chain 라이브러리가 주된 내용 

##

#### hc-key-chain.cpp

- ndn-cxx/security/key-chain.hpp 를 상속함
- key-chain.cpp 에 작성한 hash-chain 관련 내용만 포함될 수 있도록 함
  - ndn-cxx 와 분리하여 관리할 수 있도록 하기 위함

#### hc-segment-fetcher.cpp

- ndn-cxx/util/segment-fetcher.hpp 를 상속함
- hash-chain 을 검증할 수 있는 루틴이 포함될 수 있도록 함

#### tlv 를 활용한 next-hash 구성

- 현재, difs-cxx 의 hash-chain 브렌치에 next-hash 구성은 데이터 앞 32 바이트를 추가하는 형태
- 오버헤드를 줄이기 위한 방안으로 tlv 에 next-hash 를 구성할 수 있도록 함
  - appMetaInfo 로 정의된 tlv 를 next-hash 로 사용
- **위 내용은 제안사항으로 가능/불가능 여부를 먼저 판단할 필요가 있음**
- **시간이 소요되는 경우 tlv 를 활용한 next-hash 구성은 동적노드구성 이후로 미룸**

#### ndn-cxx0.7.1 적용

- ndn-cxx0.7.1 로 업데이트 되면서 여러 수정이 진행됨
  - signature 및 validator 관련 수정이 진행된 관계로 이를 수용할 필요가 있음
- 특히, 관련 버그를 발견하고 NDN 커뮤니티에 리포팅한 관계로 버그 수정 기능이 반드시 필요함
  - NDN 커뮤니티에서 해당 버그 수정 중
- **위 내용은 NDN 커뮤니티의 스케줄에 따라 진행할 예정**
  - **동적노드구성 이후로 미룸**

##

#### ndnputfile

- ndnputchunk 에 작성된 hash-chain 관련 내용 ndnputfile 적용
  - DIFS 의 hash-chain 브렌치

#### write-handler.cpp

- 현재, DIFS 의 write_handler 에서 SegmentFetcher 를 사용하여 segInit, onSegmentData, onSegmentTimeout 에 사용중
  - hc_segment_fetcher 를 활용하여 데이터가 DIFS 에 저장되기 전 hash-chain 검증할 수 있도록 함
  - DIFS 의 hash-chain 브렌치

#### ndngetfile

- ndngetfile 을 통해 데이터를 제공받은 소비자가 받은 데이터를 검증할 수 있도록 지원
  - DIFS 의 hash-chain 브렌치

_Originally posted by @uni2u in https://github.com/uni2u/difs-cxx/issues/3#issuecomment-806315798_

**Comment by uni2u** [comment]
- 의문사항, 요구사항은 코멘트를 이용해주세요

**Comment by uni2u** [comment]
- 진행 현황을 알려주시기 바랍니다.

**Comment by uni2u** [comment]
- ndn-cxx 0.7.1 적용 및 ndn-tools 동작 확인
- appMetaInfo 의 경우 다른 타입의 블럭으로 정의되어 있으며 기존 새 타입을 추가하여 hash-chain 구성 방안과 같을 것으로 추정
- hc-key-chain, hc-segment-fetcher, ndnputfile, ndngetfile 등 (김성호 팀장 인계)

**Comment by uni2u** [comment]
- tlv 를 이용한 next-hash 적용
  - appMetaInfo 적용 가능성에 대한 부분 체크중 (@justin-labry)
    - 가능성 여부 체크시 문의사항이 있을 수 있습니다. (@tribela)

- 개발진행) hc-key-chain, hc-segment-fetcher
  - 현재 upgrade-0.7.1 브렌치 기반으로 작성
  - 데이터 필드의 앞 32 바이트에 next-hash 적용 모델 기준
  - 주의) 추후 tlv 적용이 문제없이 가능한 경우 tlv 기반 hahs-chain 으로 교체

- 개발진행) ndnputfile, ndngetfile, writehandler
  - upgrade-0.7.1 브렌치 기반 내용이 nosql, command parameter 등과 잘 융합될 수 있어야 함
  - difs/mongodb 브렌치를 기준
  - producer 가 ndnputfile 이후 DIFS 는 저장된 데이터를 varify 하기 위해 hc-segment-fetcher 사용

**Comment by sungho-gurumnet** [comment]
Hash Content 포맷 확인 부탁드립니다.
=======================================================================
Data = DATA-TYPE TLV-LENGTH
         Name
         [MetaInfo]
         [Content]
         DataSignature

Content = CONTENT-TYPE TLV-LENGTH
                                               HashContent
                                               NextHash

HashContent = HASH_CONTENT_TYPE(900) TLV-LENGTH - Octet

NextHash = NEXT_HASH_TYPE(901) TLV_LENhttps://github.com/uni2u/difs/blob/documents/meet/20200701-hash_chain.pdfGTH(32) - Octet

=======================================================================

DataSignature = SignatureInfo SignatureValue

SignatureInfo = SIGNATURE-INFO-TYPE TLV-LENGTH
                  SignatureType
                  [KeyLocator]

SignatureValue = SIGNATURE-VALUE-TYPE TLV-LENGTH *OCTET

| Type | Value |
|---|:---:|
| `DigestSha256` | 0 |
| `DigestSha256WithRsa` | 1 |같
| `DigestSha256WithEcdsa` | 3 |
| `SignatureHmacWithSha256` | 4 | 
| `DigestBlake2s` | 6 |
| `DigestBlake3` | 7 |
| `DigestSha256WithHashChain` | 8 |
| `DigestSha256WithRsaWithHashChain` | 9 |                        < = Type이 명확히 정의가 안되어 있는것 같은데, 이런식으로 정의해도 괜찮은지 확인 부탁드립니다.
=======================================================================

**Comment by uni2u** [comment]
- type 확인합니다.
- 첫번째 패킷은 RSA 로 signature 를 적용하며 두번째 패킷부터는 hash 를 적용합니다.

**Comment by uni2u** [comment]
- HashContent 확인했습니다.
- HashChain Type 확인했습니다.

**Comment by uni2u** [comment]
```
+------------------------------------------+
|                   Name                   |
+------------------------------------------+
|                 MetaInfo                 |
|(ContentType,FreshnessPeriod,FinalBlockID)|  --->  appMetaInfo 등 기존것을 활용하는 방안 (Next Hash)
+------------------------------------------+
|                  Content                 |
+------------------------------------------+
|                 Signature                |
+------------------------------------------+
|SignatureInfo                             |
|            +----------------------------+|
|            | SignatureType              ||
|            +----------------------------+|
|            | KeyLocator                 ||
|            +----------------------------+|
+------------------------------------------+
|              SignatureValue              |
+------------------------------------------+
```

```
+----------------------+         +--------------+         +--------------+
|+--------------------+|         |+------------+|         |+------------+|
||data                ||         ||data        ||         ||data        ||
|+--------------------+|         |+------------+|         |+------------+|
||DigestSHA256        || <--+    ||DigestSHA256|| <--+    ||000000000000||
|+--------------------+|    |    |+------------+|    |    |+------------+|
+----------------------+    |    +--------------+    |    +--------------+
|SignatureSha256WithRsa|    +--- |DigestSHA256  |    +--- |DigestSHA256  |
+----------------------+         +--------------+         +--------------+
```

**Comment by sungho-gurumnet** [comment]
말씀해주신 MetaInfo에 appMetaInfo에 넣는 방식으로 진행 중입니다.
appMetaInfo안에 들어갈 수 있는 블록의 경우 128~252번까지의 Type을 허용하기 때문에 다음과 같이 정의할까 합니다.

SignatureValue = SIGNATURE-VALUE-TYPE TLV-LENGTH *OCTET

AppMetaInfo ::= HASH-CHAIN-TYPE(128) - TLV-LENGTH
                          SignatureValue

혹은 불필요한 TYPE, LENGTH 가 반복되는것을 생략하여 

AppMetaInfo ::= HASH-CHAIN-TYPE(128) - TLV-LENGTH *OCTET

이런식으로도 정의가 가능할 것으로 보이는데, 제 생각에는 SignatureValue를 그대로 넣는 것이 더 낫지 않을까 합니다.

의견 부탁드립니다.

**Comment by uni2u** [comment]
appMetaInfo 관련 블록 확인은 미처 못했네요.

HashChainType: 128, SignatureValue 를 재활용하는 방법에 동의합니다.

**Comment by uni2u** [comment]
- HashChain 에서 첫번째 패킷의 Signature 는 ECDSA 로 합니다.
  - NDN 의 기본 Signature 가 ECDSA 이며 적어도 RSA 보다는 좋은 성능을 보이기 때문입니다.

**Comment by sungho-gurumnet** [comment]
넵 알겠습니다.

기본값을 ECDSA로 진행하도록 하겠습니다.

**Comment by sungho-gurumnet** [comment]
metaInfo를 이용하여 해시 체인을 구성하려고 시도 하였으나, 현재 NFD 내부적으로 metaInfo를 허용하지 않는 것으로 보입니다.(혹은 cxx)
https://ndnsim.net/2.1/doxygen/classndn_1_1MetaInfo.html#details 

metaInfo를 설정하여 data 패킷을 전송할 경우 nfd에서 data를 drop시키는 것을 확인하였고,
![image](https://user-images.githubusercontent.com/8456262/117931314-00eded80-b33a-11eb-8c62-106f277234df.png)

nfd의 옵션을 바꿔서 무조건 drop이 아닌, 캐시되도록 허용을 하여도 interest와 매칭이 안되는 현상을 확인하였습니다.
![image](https://user-images.githubusercontent.com/8456262/117931428-21b64300-b33a-11eb-8227-2378e9af966a.png)

* 정상 동작인 경우 아래와 같이 응답이 됩니다.
![image](https://user-images.githubusercontent.com/8456262/117931780-92f5f600-b33a-11eb-95c2-2da9cf96a57a.png)

이 부분은 NFD를 수정하지 않는한 해결이 되지 않을 것으로 보이는 부분이라 현재 가능한 방법은 next hash를 content에 포함시키는 방법이 최선이지 않을까 합니다.

**Comment by uni2u** [comment]
@sungho-gurumnet 수고 많으셨습니다. 확인 감사드립니다.

말씀하신 내용은 저희가 걱정했던 부분입니다.

그럼 기존 계획대로 **_Content 에 Next Hash 를 적용 (현재) 하는 구조로 활용_** 으로 하겠습니다.

**Comment by sungho-gurumnet** [comment]
Content = CONTENT-TYPE TLV-LENGTH *OCTET

=>
Content = CONTENT-TYPE TLV-LENGTH
                 RealContent
                 SignatureValue

RealContent = CONTENT-TYPE TLV-LENGTH *OCTET

SignatureValue = SIGNATURE-VALUE-TYPE TLV-LENGTH *OCTET

위처럼 진행하거나 RealContent의 CONTENT-TYPE을 다른 타입으로 재 정의해서 사용하면 되지 않을까 합니다.

**Comment by uni2u** [comment]
Content = CONTENT-TYPE TLV-LENGTH *OCTET

=>
Content = CONTENT-TYPE TLV-LENGTH
RealContent
SignatureValue

RealContent = CONTENT-TYPE TLV-LENGTH *OCTET

SignatureValue = SIGNATURE-VALUE-TYPE TLV-LENGTH *OCTET

내용이 맞을 듯 합니다.

- 개발에 오버헤드가 많이 발생하지 않는 방향으로 진행하는 것으로 합시다.

**Comment by taewoong0627** [comment]
현재 Producer 최적화를 진행중입니다.

1. 기존 Producer 
기존 Producer가 동작하는 방식은 파일을 차레대로 읽어온 후 읽어온 파일을 m_store 라는 vector 에 저장한 다음 m_store를 뒤에서 부터 읽어 Data 를 만드는 방식으로 구현이 되어있습니다.

```
// 파일 저장 및 읽기
  while (is.good()) {
    is.read(reinterpret_cast<char*>(buffer.data()), buffer.size());
    const auto nCharsRead = is.gcount();

    if (nCharsRead > 0) {
      auto data = make_shared<Data>(Name(m_versionedPrefix).appendSegment(m_store.size()));
      data->setFreshnessPeriod(m_options.freshnessPeriod);
      Block content(tlv::Content);
      Block realContent = makeBinaryBlock(tlv::Content, buffer.data(), nCharsRead);
      content.push_back(realContent);
      data->setContent(content);

      // data->setContent(buffer.data(), static_cast<size_t>(nCharsRead));
      m_store.push_back(data);
    }
  }

// 데이터 생성
  auto finalBlockId = name::Component::fromSegment(m_store.size() - 1);

  Block nextHash(tlv::SignatureValue);
  for (auto it = m_store.rbegin(); it != m_store.rend(); it++) {
    Data& data = **it;
    data.setFinalBlock(finalBlockId); 

    auto content = data.getContent();
    content.push_back(nextHash);

    data.setContent(content);

    if (it == m_store.rend() - 1) {
      m_keyChain.sign(data);
    } else {
      m_keyChain.sign(data, ndn::signingWithSha256());
    }

    nextHash = data.getSignatureValue(); //32byte
  }
```


2. 수정된 Producer
수정된 Producer는 처음부터 파일을 뒤에서 읽어 Data 를 만드는 방식으로 구현을 하였습니다.

```
  int chunkSize = end_pos / m_options.maxSegmentSize;
  int lastDataSize = end_pos % m_options.maxSegmentSize;
  auto finalBlockId = name::Component::fromSegment(chunkSize);

  std::vector<uint8_t> buffer(m_options.maxSegmentSize);
  Block nextHash(tlv::SignatureValue);

  for(int count = 0; count <= chunkSize; count++) {
    if(count == 0) {
      is.seekg(end_pos - lastDataSize);
      is.read(reinterpret_cast<char *>(buffer.data()), lastDataSize);     
    } else {
      is.seekg(end_pos - lastDataSize - buffer.size() * count);
      is.read(reinterpret_cast<char *>(buffer.data()), buffer.size());
    }

    const auto nCharsRead = is.gcount();

    if(nCharsRead > 0) {
      auto data = make_shared<Data>(Name(m_versionedPrefix).appendSegment(chunkSize - count));
      data->setFreshnessPeriod(m_options.freshnessPeriod);
      Block content(tlv::Content);
      Block realContent = makeBinaryBlock(tlv::Content, buffer.data(), nCharsRead);
      content.push_back(realContent);
      content.push_back(nextHash);
      data->setContent(content);
      data->setFinalBlock(finalBlockId);

      if(count == chunkSize) {
        m_keyChain.sign(*data);
      } else {
        m_keyChain.sign(*data, ndn::signingWithSha256());
      }
      nextHash = data->getSignatureValue();

      m_store.insert(m_store.begin(), data);
    } else {
      std::cerr << "Data read failed" << std::endl;
      return;
    }
  }

```

1번과 2번의 동작 시간을 측정한 결과, 작은 파일에서는 2번의 동작 시간이 약 20~30% 가량 성능 향상이 되었습니다. 하지만 파일의 크기가 커질수록 성능이 하락되는 것을 확인하였습니다. (2번의 성능 하락 원인은 현재 읽는 위치를 바꾸기 위해 seekg 함수를 계속 호출함으로 동작 시간이 길어지는 것으로 추측됩니다.)

Producer 최적화 방법에 대하여 생각해두신 방법이나, 좋은 방법이 있으시면 의견 부탁드리겠습니다.

감사합니다.

**Comment by uni2u** [comment]
- 성능 향상이 조금이라도 있다면 좋은 소식입니다. ^^
- 아무래도 파일이 크면 성능이 저하될 수 밖에 없을 것으로 보입니다.
- 어쩔 수 없이 파일 전체를 읽은 후 해시를 계산하고 데이터 블록을 만들기 때문입니다.
- 성능은 물론 20년도 VS 21년도 의 차이도 있겠지만 NDN 기본 서명 구조인 RSA/ECDSA 와의 비교를 생각하고 있습니다.
  - 20년도 기준으로 ndnpufile 성능을 측정하면 ECDSA 와 거의 같은 수준을 보입니다.
    - ECDSA 는 블록 만들면 바로바로 전송하지만
    - DIFS 는 파일을 우선 읽고 블록을 만들어야 합니다.
  - 단, NFD 등의 내용을 완전 제거한 순수한 내용만으로 비교하면 DIFS HashChain 이 약 1배 빠릅니다.
  - 결과적으로 HashChain 이 RSA 나 ECDSA 보다 성능이 우수한 점을 피력하고자 합니다.
    - 즉, 20년도의 비교 성능과 21년도의 비교 성능을 비교했을때 21년도 성능이 우수함을 보이는 방법 입니다.
- 여기저기 자료를 찾아보고 하고 있습니다
  - hash chain 등의 검색어로 open source 등을 보고 있습니다.
  - 특별한 내용은 현재까지 보이지 않고 가능성만 알 수 있을 코드가 많습니다.
---
- HashChain 최적화 관련 특별한 방법은 점차 찾아가는 것으로 하고
- 우선은 수정된 Producer 를 기준으로 진행하는 것이 좋아보입니다.
  - 작은 파일에서 기존 producer 대비 20%~30% 향상이라면
  - 큰 바일에서도 기존 producer 대비 성능 향상이 있어보입니다.

**Comment by uni2u** [comment]
위 내용에 이어서...

difs 의 ndnputfile 에 현재 다음과 같이 적용하고 있습니다.

```
  int dataSize = blockSize - util::HASH_SIZE;
  std::array<uint8_t,util::HASH_SIZE> hash;
  std::array<uint8_t,util::HASH_SIZE> prevHash;
  uint8_t *buffer = new uint8_t[blockSize];

  int position;
  for (position = dataSize; position < (int)m_bytes ; position += dataSize) {
    if (!hashes.empty()) {
      prevHash = hashes.front();
    }
    memcpy(buffer, prevHash.data(), util::HASH_SIZE);
    // This part is to read from the behind.
    insertStream->seekg(-position, std::ios::end);
    auto readSize = boost::iostreams::read(*insertStream, reinterpret_cast<char*>(buffer + util::HASH_SIZE), dataSize);
    if (readSize <= 0) {
      BOOST_THROW_EXCEPTION(Error("Error reading from the input stream"));
    }

    std::streambuf* buf;
    buf = std::cout.rdbuf();
    std::ostream os(buf);

    hash = util::calcHash(buffer, blockSize);

    hashes.push_front(hash);

  // save first block size
  // If position >= m_bytes, only one block is generated and no hash chain
  m_firstSize = m_bytes - (position - dataSize);
  //std::cout << "first data size = " << m_firstSize << std::endl;
  insertStream->seekg(0, std::ios::beg);
```

**Comment by taewoong0627** [comment]
**hc-key-chain.cpp**

```
namespace ndn {
namespace security {
inline namespace v2{
class HCKeyChain : protected KeyChain {
public:
  HCKeyChain() : KeyChain() {};

  void
  sign(std::vector<shared_ptr<Data>> m_store, const SigningInfo &params);

  void
  sign(Data &data, const ndn::Block &nextHash);

  void
  sign(Data &data, const ndn::Block &nextHash, const SigningInfo &params);
};
}
}
using security::v2::HCKeyChain;
}
```
다음과 같이 class 를 생성하여 진행하고 있습니다.

**Comment by taewoong0627** [comment]
**hc-key-chain.cpp**
```
namespace ndn {
namespace security {
inline namespace v2{
class HCKeyChain : protected KeyChain {
public:
  HCKeyChain() : KeyChain() {};

  void
  sign(std::vector<shared_ptr<Data>> m_store, const SigningInfo &params);

  void
  sign(Data &data, const ndn::Block &nextHash);

  void
  sign(Data &data, const ndn::Block &nextHash, const SigningInfo &params);
};
}
}
using security::v2::HCKeyChain;
}
```
현재 HCKeyChain 은 위와 같이 class 를 정의해 두고 진행하면서 sign 함수 관련 질문이 있어 이슈를 남깁니다.

1. 아래와 같은 함수의 형태로 진행할 경우 difs-cxx 내에서 HashChain 작업을 다 진행함으로, 사용자는 Data를 생성하여 m_store 에 넣어 sign 함수를 실행하면 되는 형태입니다.

```
void
sign(std::vector<shared_ptr<Data>> m_store, const SigningInfo &params);

//사용자

while (is.good()) {
  is.read(reinterpret_cast<char*>(buffer.data()), buffer.size());
  const auto nCharsRead = is.gcount();

  if (nCharsRead > 0) {
    auto data = make_shared<Data>(Name(m_versionedPrefix).appendSegment(m_store.size()));
    data->setFreshnessPeriod(m_options.freshnessPeriod);
    Block content(tlv::Content);
    Block realContent = makeBinaryBlock(tlv::Content, buffer.data(), nCharsRead);
    content.push_back(realContent);
    data->setContent(content);
    data->setFinalBlock(finalBlockId);
    m_store.push_back(data);
  }
}

m_keyChain.sign(m_store, ndn::signingWithSha256);
```
2. 아래와 같은 방법은 현재 difs-cxx에 적용되어 있는 방법으로, 사용자가 직접 데이터의 끝을 구분하여 sign 함수를 실행시켜야 하는 형태입니다.

```
void
sign(Data &data, const ndn::Block &nextHash);

void
sign(Data &data, const ndn::Block &nextHash, const SigningInfo &params);

// 사용자

if(count == chunkSize) {
  m_keyChain.sign(*data);
} else {
  m_keyChain.sign(*data, ndn::signingWithSha256());
}
```
1번 함수의 장점으로는 사용자가 편리하게 사용할 수 있습니다. 하지만 단점으로는 producer의 최적화를 진행할 수 없게됩니다.

2번 함수의 장점으로는 위에 올렸던 코드와 같이 producer의 최적화를 진행하게 될 시 호출하여 사용할 수 있으므로 성능개선을 할 때 사용할 수 있습니다. 하지만 단점으로는 사용자가 직접 데이터를 구분하여 실행시켜 주어야합니다.

개인적인 생각으로는 producer 의 최적화를 진행하실 예정이라면 2번 형태의 함수를 사용하는 것이 좋다고 생각하며, producer의 최적화 없이 기존 방식대로 진행하실 예정이라면 1번 형태의 함수를 사용하는 것이 좋다고 생각됩니다.

다른 형태의 함수나 더 좋은 방법이 있으시면 의견 부탁드립니다.

**Comment by uni2u** [comment]
- producer 는 difs 라이브러리를 사용하여 application 을 구성할 수 있는 사람을 의미합니다.
  - 즉, difs 라이브러리를 사용한 ndnputfile.cpp 같은 application 이 실행됨
  - 사용자를 위한 difs 라이브러리가 제공되기에 최적화를 진행하는 것이 좋습니다.
- producer 의 최적화가 가능한 모델을 진행하는 것이 좋을 듯 합니다.
  - 결국엔 difs 성능 최적화가 되는 것 이겠지요. (저장 속도가 빠름)

**Comment by taewoong0627** [comment]
**hc-segment-fetcher.cpp**

추가로 segment-fetcher 작업도 진행중에 상속 이슈가 있습니다.

```
namespace ndn {
namespace util {
class HCSegmentFetcher : protected SegmentFetcher 
{
    HCSegmentFetcher(Face& face, security::v2::Validator& validator, const Options& options) 
    : SegmentFetcher(face, validator, options) {};

    HCSegmentFetcher(Face& face, const Interest& baseInterest, security::v2::Validator& validator, const Options& options) {
        SegmentFetcher::start(face, baseInterest, validator, options)
    };
}; 
}
}
```
위와 같이 두가지 방식으로 시도하였지만, SegmentFetcher 의 생성자가 private 로 설정되어있어 직접 생성이 불가능하며, start 함수를 통해 생성을 시도하면 SegmentFetcher 의 기본 생성자가 존재하지 않아 오류가 발생하고 있습니다.

현재 팀장님과 얘기 후 나온 방안은 SegmentFetcher 를 상속받지않고 멤버변수로 넣어 사용하는 방식입니다.
또는 SegmentFetcher를 그대로 가져와 HCSegmentFetcher 로 변경 후 HashChain 검증 부분을 넣어 만드는 방식이 있습니다.

SegmentFetcher 상속에 관하여 의견 부탁드립니다.

**Comment by uni2u** [comment]
```
- hc-segment-fetcher.cpp
  - ndn-cxx/util/segment-fetcher.hpp 를 상속함
  - hash-chain 을 검증할 수 있는 루틴이 포함될 수 있도록 함
```

라고 계획을 잡았었습니다.

이 부분은 무엇보다도 ndn-cxx 의 파일을 직접 수정하지 않고 HashChain 을 구성하기 위함입니다.
(물론 HCKeyChain 도 마찬가지 입니다.)

ndn-cxx 은 ndn 커뮤니티에서 작성한 코드이다 보니 메인 코드에 . 하나 추가하는 것도 부담스러움이 있습니다.

하여 ndn-cxx 코드는 수정하지 않기 위해서 `hc-key-chain.cpp` 및 `hc-segment-fetcher.cpp` 를 제안한 것 입니다.

즉, ndn-cxx 에 직접적인 수정을 하지 않는다면 어떠한 방법이든 문제 없습니다.

- segment-fetcher.cpp 에 수정이 없는 방안을 우선시 합니다.
  - hc-segment-fetcher.cpp 생성 - 검증과정 포함

**Comment by taewoong0627** [comment]
**hc-segment-fetcher.cpp** 관련 이슈입니다.

```
void
HCSegmentFetcher::afterValidationSuccess(const Data& data) {
  std::cout << data << std::endl;
  int segment_no = data.getName().get(-1).toSegment();
  auto content = data.getContent();
  std::cout << "content length: " << content.size() << std::endl;
  content.parse();

  if(hash_data.size() != 0 && hash_data.find(segment_no+1)->second != 0) {
    auto cData = hash_data.find(segment_no+1)->second;
    auto m_content = cData->getContent();
    m_content.parse();
    auto hash_block = m_content.get(tlv::SignatureValue);
    if (memcmp((void*)content.get(tlv::SignatureValue).value(), (void*)hash_block.value(), data.getSignatureValue().value_size())) {
      onError(HASHCHAIN_ERROR, "Failure hash key error");
    } else {
      hash_data.erase(segment_no+1);
      afterSegmentValidated(data);
    }
  } else {
    for (auto iter = content.elements_begin(); iter != content.elements_end(); iter++) {
      if(iter->type() == tlv::SignatureValue) {
        auto signature_block = iter.base();
        std::shared_ptr<Block> block = std::make_shared<Block>(*signature_block); 
        hash_map.insert(std::pair<int, std::shared_ptr<Block>>(segment_no, block));
      }
    }
  }

  if(segment_no != 0){
    auto hash_block = hash_map.find(segment_no-1)->second;
    if(hash_block == 0) {
      std::shared_ptr<Data> m_data = std::make_shared<Data>(data); 
      hash_data.insert(std::pair<int, std::shared_ptr<Data>>(segment_no, m_data));
    } else if (memcmp((void*)data.getSignatureValue().value(), (void*)hash_block->value(), data.getSignatureValue().value_size())) {
      onError(HASHCHAIN_ERROR, "Failure hash key error");
    } else {
      hash_data.erase(segment_no-1);
      afterSegmentValidated(data);
    }
  } else {
    afterSegmentValidated(data);
  }
}
```

현재 hc-segment-fetcher의 afterValidationSuccess 함수입니다.
위 함수의 동작방법은 0, 1, 2, 3의 Data가 차례대로 왔을시에 자신의 앞에 온 Data의 nextHash 값을 꺼내 현재 자신의 Hash 값과 비교하는 역할을 하고, 추가적으로 0, 2, 3, 1 순서로 Data가 왔을 시에 2번 Data는 검증을 바로 받지 못하므로 map에 Data를 저장해두고 1번 데이터가 도착 시에 검증을 하는 방식입니다.

위와 같이 동작할 때 문제점이 있습니다. 2번 Data는 아직 검증을 받지 못한 상황인데, 3번 Data의 기준으로 보았을 때 2번 Data는 도착을 한 상황이므로, nextHash 값을 꺼내 비교를 하게됩니다. 제대로 검증이 되지 않은 Data에서 Hash 값을 가져와 비교를 하기 때문입니다. 

현재 구현되어 있는 상태로 진행하게되면, 만약 1번 Data의 값이 이상해 검증에 실패한다면 Error 를 보내게 되므로, 큰 문제는 없을 것으로 보입니다. 하지만 꼭 Data 를 차례대로 다 검증하고 넘어가야한다면 다음과 같은 문제가 발생할 수 있습니다. 우선 Data를 memory 에 쌓아놓는 형태이기 때문에 큰 Data를 전송 시에 0, 2, 3, ..... 1 번 순서대로 오게 된다면 오랜 시간이 걸릴 수 있고, memory를 많이 사용 하게 됩니다.

어떠한 방식으로 진행해야하는지 의견 부탁드립니다.

**Comment by uni2u** [comment]
- 좋은 질문입니다. 위 문제는 두고두고 고민할 내용입니다.
- 우선, 데이터 검증은 차례로 검증되는 구조가 맞습니다.
  - HashChain 의 검증 구조가 그럴 수 밖에 없습니다.
- 반면, 데이터 패킷 전송은 차례로 되지 않습니다.
  - 순서대로 받지 못한 데이터가 있기 때문에 map 에 저장하는 구조를 사용합니다.
- 이러한 모습으로 예상하고 있는 문제가 발생할 수 있습니다.
  - 문제에 대한 솔루션은 조금 천천히 생각하고자 합니다.
    - 상당히 복잡한 문제라 해결이 쉽지 않을 듯 합니다.
    - 좋은 의견 있으시면 알려주세요.
  - 우선 패킷은 차례대로 들어온다는 가정하에 진행합시다.

**Comment by taewoong0627** [comment]
**AppMetaInfo 적용 관련** 

현재 말씀해주신 방법으로 AppMetaInfo 를 적용시켜 확인해본 결과입니다.

```
    auto data = make_shared<Data>(interest.getName());
    data->setContent(reinterpret_cast<const uint8_t*>(content.data()), content.size());
    
    Block block(tlv::AppPrivateBlock1);
    MetaInfo meta;
    meta.addAppMetaInfo(block);

    std::cout << meta << std::endl;

    data->setMetaInfo(meta);
    data->setFreshnessPeriod(10_s);
    // Sign Data packet with default identity
    m_keyChain.sign(*data);
```
위 코드와 같이 MetaInfo 에 addAppMetaInfo 함수로 block을 등록하였고 setMetaInfo 로 meta를 세팅한후 setFreshnessPerfiod 를
설정해주면 제대로 동작하는 것을 확인하였습니다. 이 부분을 적용하여 hash-chain 부분을 AppMetaInfo 에 넣는걸로 수정 진행하면 될까요?

- producer 
![image](https://user-images.githubusercontent.com/64938848/126252205-86f2fc37-b1fa-4580-a242-2be49a14555b.png)

- consumer
![image](https://user-images.githubusercontent.com/64938848/126252245-973c4c66-0e55-4f46-bfb4-6086d66e3533.png)

**Comment by uni2u** [comment]
@taewoong0627 아주 감사합니다. difs-cxx 에 적용해 봅시다!

**Comment by taewoong0627** [comment]
**TLV Type**

적용을 하려면 TLV Type 을 추가해야합니다.
현재 AppMetaInfo의 Type 적용 가능한 숫자는 128~255입니다. 

혹시 nextHash Block의 Type 의 이름과 번호를 몇번으로 지정해야할지 말씀해주시면 그대로 적용하겠습니다.

**Comment by uni2u** [comment]
@taewoong0627 음... 크게 생각해보지 않았습니다. 번호는 기억하기 쉽도록 111 또는 222 로 하고 TYPE 이름은 HASHCHAIN 또는 NEXTHASH 등으로 하면 어떨까 싶은데 편하신 것으로 정하시고 알려주시면 참고하겠습니다.

**Comment by taewoong0627** [comment]
**Type**

tlv type 을 222번 tlv::HashChain 으로 사용할수있도록 추가하였습니다.

**Comment by uni2u** [comment]
> **Type**
> 
> tlv type 을 222번 tlv::HashChain 으로 사용할수있도록 추가하였습니다.

tlv type 222 (tlv::HashChain) 을 확인합니다.

**Comment by uni2u** [comment]
수정 버전을 기반으로 간단한 테스트 시 ndngetfile TIMEOUT 발생 가능성이 있음

- 반드시 발생하는 것이 아니기에 확정지을 수 없음
  - 또한, appMetaInfo 를 사용하면 패킷 drop 이 있을 수 있다고 하였는데
  - packet drop 으로 인하여 발생한 것인지 확실하지 않음
- content 필드에 next-hash 를 넣은 버전은 더미 데이터의 값(알 수 없는 부호)이 프린트 되기에 확인 가능
- appMetaInfo 활용 버전의 경우 이 값이 프린트 되지는 않음 (반드시 프린트 할 필요는 없음)
  - 단, 어떤 경우 프린트 대신 TIMEOUT 이라는 메시지가 발생함 (NFD 로그에서 발생하는 것이 아님)
- push 하기 전 각자가 64M, 1G 더미 파일에 대한 ndnputfile 테스트를 진행할 필요 있음
